# Generated by Django 5.2.5 on 2025-08-17 21:20

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_saque', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taxa de Saque (%)')),
                ('saque_minimo', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Saque Mínimo (Kz)')),
                ('horario_saque_inicio', models.TimeField(default=datetime.time(8, 0), verbose_name='Início Horário de Saque')),
                ('horario_saque_fim', models.TimeField(default=datetime.time(18, 0), verbose_name='Fim Horário de Saque')),
                ('link_grupo_whatsapp', models.URLField(blank=True, null=True, verbose_name='Link do Grupo WhatsApp')),
                ('link_grupo_telegram', models.URLField(blank=True, null=True, verbose_name='Link do Grupo Telegram')),
                ('link_apoio_whatsapp_cadastro', models.URLField(blank=True, null=True, verbose_name='Link de Apoio WhatsApp (Pág. Cadastro)')),
            ],
            options={
                'verbose_name': 'Configuração da Plataforma',
                'verbose_name_plural': 'Configurações da Plataforma',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_nivel', models.CharField(max_length=100, unique=True, verbose_name='Nome do Nível')),
                ('deposito_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Depósito Mínimo para Alugar (Kz)')),
                ('ganho_diario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho Diário (Kz)')),
                ('ciclo_dias', models.IntegerField(verbose_name='Ciclo de Duração (dias)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='niveis_imagens/', verbose_name='Imagem do Nível')),
            ],
            options={
                'verbose_name': 'Nível de Investimento',
                'verbose_name_plural': 'Níveis de Investimento',
            },
        ),
        migrations.CreateModel(
            name='PlatformBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(max_length=100, unique=True, verbose_name='Nome do Banco')),
                ('nome_titular_conta', models.CharField(max_length=200, verbose_name='Nome do Titular da Conta')),
                ('iban', models.CharField(max_length=30, unique=True, verbose_name='IBAN')),
            ],
            options={
                'verbose_name': 'Detalhe Bancário da Plataforma',
                'verbose_name_plural': 'Detalhes Bancários da Plataforma',
            },
        ),
        migrations.CreateModel(
            name='PremioSubsidio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Prêmio (Kz)')),
                ('chance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Chance (0.00 a 100.00)')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Prêmio de Subsídio',
                'verbose_name_plural': 'Prêmios de Subsídio',
                'ordering': ['-chance'],
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(verbose_name="Conteúdo da Página 'Sobre'")),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': "Conteúdo 'Sobre'",
                'verbose_name_plural': "Conteúdo 'Sobre'",
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Número de Telefone')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nome de Usuário')),
                ('invitation_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de Convite')),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Geral')),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Disponível para Saque')),
                ('saldo_subsidio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo de Subsídios')),
                ('total_sacado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Sacado')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('can_spin_roulette', models.BooleanField(default=False, verbose_name='Pode Abrir Prêmio')),
                ('spins_remaining', models.IntegerField(default=0, verbose_name='Prêmios Restantes para Abrir')),
                ('last_spin_reset', models.DateTimeField(blank=True, null=True, verbose_name='Último Reset de Prêmios')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL, verbose_name='Convidante')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='ClientBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Banco')),
                ('nome_titular_conta', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Titular da Conta')),
                ('iban', models.CharField(blank=True, max_length=30, null=True, verbose_name='IBAN')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Detalhe Bancário do Cliente',
                'verbose_name_plural': 'Detalhes Bancários dos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Depósito (Kz)')),
                ('comprovativo_imagem', models.ImageField(upload_to='comprovantes_depositos/', verbose_name='Comprovativo de Depósito')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('data_deposito', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Depósito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
        migrations.CreateModel(
            name='NivelAlugado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de Expiração')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está Ativo?')),
                ('ultima_tarefa', models.DateTimeField(blank=True, null=True, verbose_name='Última Tarefa Realizada')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.nivel', verbose_name='Nível Alugado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveis_alugados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Nível Alugado',
                'verbose_name_plural': 'Níveis Alugados',
            },
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='renda_geral', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Renda do Usuário',
                'verbose_name_plural': 'Rendas dos Usuários',
            },
        ),
        migrations.CreateModel(
            name='Saque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Saque (Kz)')),
                ('iban_cliente', models.CharField(blank=True, max_length=30, null=True, verbose_name='IBAN do Cliente')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('data_saque', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Solicitação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saques', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Saque',
                'verbose_name_plural': 'Saques',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Realização')),
                ('ganho', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganho da Tarefa (Kz)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa Realizada',
                'verbose_name_plural': 'Tarefas Realizadas',
            },
        ),
    ]
